server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/wibuforums_identity"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: "GF8bIi7ezOnrdsZvh1gt1sHc5E8KnJaybTf88q5GecpO4E6NhR0PENFaBM+ZEyVG"
  refreshSignerKey: "7+78pvfH7Pp4WK8py2tecwSfH+Cvt56WKuWNEDOmqsEaiDwjWh2wBI56+gTMMy9S"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second

code:
  success: 1000

message:
  controller:
    user:
      delete: "User has been deleted!"
    role:
      delete: "Role has been deleted!"
    permission:
      delete: "Permission has been deleted!"
    authentication:
      change-password: "Password has been changed!"
      logout: "Account has been logged out!"

init-info:
  role: "ADMIN"
  username: admin123
  password: admin123
  email: admin@gmail.com
  phone-number: 1234567890
  first-name: Admin
  last-name: Admin

