server:
  port: 8888

app:
  api-prefix: /api

spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1

code:
  unauthenticated: 3001

message:
  unauthenticated: "Authentication Failed"