server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin

  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB

app:
  services:
    profile:
      url: "http://localhost:8081/profile"

message:
  controller:
    post:
      delete: "Post has been deleted!"
      update: "Post has been updated!"
    comment:
      delete: "Delete has been deleted!"