server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: neo4j
      password: admin123

message:
  controller:
    user-profile:
      add-friend-success: "Add friend successfully"
      add-friend-fail: "Can't add friend"
      unfriend-success: "Unfriend successfully"
      unfriend-fail: "Can't unfriend"

