server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: neo4j
      password: admin123
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

message:
  controller:
    user-profile:
      add-friend-success: "Add friend successfully"
      add-friend-fail: "Can't add friend"
      unfriend-success: "Unfriend successfully"
      unfriend-fail: "Can't unfriend"
      response-add-friend-success: "Response add friend request successfully"

app:
  kafka:
    topics:
      notification: "notification"

